import {Handle, DataHandle} from 'nclient-microfront';

class Router1567158287622 extends DataHandle{
  constructor() {
    super('router1567158287622Comp')
    this['compa3dbbd90-cd47-11e9-b9d0-5b87d4df74e4'] = {"style":{"width":"100px","height":"50px","border":"1px solid #000","position":"absolute","display":"inline-block","box-sizing":"border-box","wordBreak":"break-all","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"25px","left":"32px"},"raw":{},"type":"ndiv"};
this['compd7b16e20-cdf2-11e9-bfcb-8956ba6fdec1'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"29px","left":"182px","width":"auto","height":"auto","position":"absolute"},"raw":{"text":"button","type":{"value":"success","options":["","primary","success","info","warning","danger"],"type":"array"},"plain":false},"type":"elbutton"};
this['compf4435b00-cdf4-11e9-bfcb-8956ba6fdec1'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"173px","left":"166px","width":"auto","height":"auto","position":"absolute"},"raw":{"text":"","type":{"val":"date","options":["year","month","date","week","datetime","datetimerange","daterange"],"type":"array"},"placeholder":"","disabled":false},"type":"eldateTimePicker"};
this['compf559ad00-cdf4-11e9-bfcb-8956ba6fdec1'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"88px","left":"339px","width":"auto","height":"auto","position":"absolute"},"raw":{"text":"","placeholder":"input","disabled":false,"size":{"value":"","options":["","medium","small","mini"],"type":"array"},"type":"","resize":{"value":"","options":["","none","both","horizontal","vertical"],"type":"array"},"autofocus":false,"append":"","prepend":""},"type":"elinput"};
this['comp30cdf480-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"width":"100px","height":"50px","border":"1px solid #000","position":"absolute","display":"inline-block","box-sizing":"border-box","wordBreak":"break-all","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"232px","left":"261px"},"raw":{},"type":"ndiv"};
this['comp44e5b160-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"250px","left":"142px","position":"absolute"},"raw":{"text":"button","type":{"value":"","options":["","primary","success","info","warning","danger"],"type":"array"},"plain":false},"type":"elbutton"};
this['comp4595c780-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"33px","left":"376px","width":"auto","height":"auto","position":"absolute"},"raw":{"text":"button","type":{"value":"","options":["","primary","success","info","warning","danger"],"type":"array"},"plain":false},"type":"elbutton"};
this['comp46eb4560-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"width":"16px","height":"16px","position":"absolute","display":"inline-block","wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"142px","left":"427px"},"raw":{"name":"refresh"},"type":"elicon"};
this['comp47816ae0-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"187px","left":"442px","position":"absolute"},"raw":{"value":"1","options":[{"name":"1","value":"1"}]},"type":"elradio"};
this['comp47f05950-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"width":"16px","height":"16px","position":"absolute","display":"inline-block","wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"243px","left":"520px"},"raw":{"name":"refresh"},"type":"elicon"};
this['comp48228ce0-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"360px","left":"40px","position":"absolute"},"raw":{"value":"1","options":[{"name":"1","value":"1"}]},"type":"elradio"};
this['comp4854c070-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"158px","left":"505px","position":"absolute"},"raw":{"value":["1"],"options":[{"name":"1","value":"1"}]},"type":"elcheckbox"};
this['comp487f79f0-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"88px","left":"266px","position":"absolute"},"raw":{"text":"","placeholder":"input","disabled":false,"size":{"value":"","options":["","medium","small","mini"],"type":"array"},"type":"","resize":{"value":"","options":["","none","both","horizontal","vertical"],"type":"array"},"autofocus":false,"append":"","prepend":""},"type":"elinput"};
this['comp48a2e070-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"52px","left":"178px","position":"absolute"},"raw":{"text":"","type":{"value":"date","options":["year","month","date","week","datetime","datetimerange","daterange"],"type":"array"},"placeholder":"","disabled":false},"type":"eldateTimePicker"};
this['comp48c890e0-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"245px","left":"61px","position":"absolute"},"raw":{"url":"","fit":{"value":"","options":["","fill","contain","cover","none","scale-down"],"type":"array"},"lazy":false},"type":"elimage"};
this['comp48f0d960-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"311px","left":"68px","position":"absolute"},"raw":{"value":"1","multipleValue":["1"],"placeholder":"","multiple":false,"disabled":false,"options":[{"name":"1","value":"1"}]},"type":"elselect"};
this['comp491a5a60-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"67px","left":"52px","position":"absolute"},"raw":{"value":"","activeColor":{"value":"","type":"color"},"inactiveColor":{"value":"","type":"color"},"activeText":"active","inactiveText":"inactive","disabled":false},"type":"elswitch"};
this['comp494b2e60-cdfb-11e9-bd4f-93180e91c3f6'] = {"style":{"wordBreak":"break-all","box-sizing":"border-box","border-left":"1px #000 solid","border-right":"1px #000 solid","border-top":"1px #000 solid","border-bottom":"1px #000 solid","border-top-left-radius":"0px","border-top-right-radius":"0px","border-bottom-left-radius":"0px","border-bottom-right-radius":"0px","top":"134px","left":"25px","position":"absolute"},"raw":{"text":"","type":{"value":"date","options":["year","month","date","week","datetime","datetimerange","daterange"],"type":"array"},"placeholder":"","disabled":false},"type":"eldateTimePicker"};


  }
  init () {
    console.log('Router1567158287622 init')
  }
}

let router1567158287622 = new Router1567158287622()

let handle = new Handle({
  name: 'router1567158287622Comp',
  created () {
    router1567158287622.init()
    console.log('router1567158287622 created')
  },
  mounted () {
    console.log('router1567158287622 mounted')
  },
})

export default handle

export {
  router1567158287622
}